apiVersion: v1
kind: Service
metadata: 
  name: pro-app-svc
  namespace: ${K8S_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: pro-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
    